import yfinance as yf
import pandas as pd
from tqdm import tqdm

# Lista de emisoras que me diste
emisoras = [
    ("AC", "ARCA CONTINENTAL, S.A.B. DE C.V."),
    ("ACCELSA", "ACCEL, S.A.B. DE C.V."),
    ("ACTINVR", "CORPORACION ACTINVER, S.A.B. DE C.V."),
    ("AGRIEXP", "AGRO INDUSTRIAL EXPORTADORA, S.A. DE C.V."),
    ("AGUA", "GRUPO ROTOPLAS, S.A.B. DE C.V."),
    ("AGUILAS", "OLLAMANI, S.A.B"),
    ("AHMSA", "ALTOS HORNOS DE MEXICO, S.A. DE C.V."),
    ("ALFA", "ALFA, S.A.B. DE C.V."),
    ("ALPEK", "ALPEK, S.A.B. DE C.V."),
    ("ALSEA", "ALSEA, S.A.B. DE C.V."),
    ("ALTERNA", "ALTERNA ASESORIA INTERNACIONAL, S.A.B. DE C.V."),
    ("AMX", "AMERICA MOVIL, S.A.B. DE C.V."),
    ("ANB", "ANHEUSER-BUSCH INBEV SA/NV"),
    ("ARA", "CONSORCIO ARA, S.A.B. DE C.V."),
    ("ARISTOS", "CONSORCIO ARISTOS, S.A.B. DE C.V."),
    ("ASUR", "GRUPO AEROPORTUARIO DEL SURESTE, S.A.B. DE C.V."),
    ("AUTLAN", "COMPAÑIA MINERA AUTLAN, S.A.B. DE C. V."),
    ("AXTEL", "AXTEL, S.A.B. DE C.V."),
    ("AZTECA", "TV AZTECA, S.A.B. DE C.V."),
    ("BBAJIO", "BANCO DEL BAJÍO, S.A., INSTITUCIÓN DE BANCA MÚLTIPLE"),
    ("BBVA", "BANCO BILBAO VIZCAYA ARGENTARIA, S.A."),
    ("BEVIDES", "FARMACIAS BENAVIDES, S.A.B. DE C.V."),
    ("BIMBO", "GRUPO BIMBO, S.A.B. DE C.V."),
    ("BOLSA", "BOLSA MEXICANA DE VALORES, S.A.B. DE C.V."),
    ("CABLE", "EMPRESAS CABLEVISION, S.A. DE C.V."),
    ("CADU", "CORPOVAEL S.A.B. DE C.V."),
    ("CEMEX", "CEMEX, S.A.B. DE C.V."),
    ("CHDRAUI", "GRUPO COMERCIAL CHEDRAUI, S.A.B. DE C.V."),
    ("CIDMEGA", "GRUPE, S.A.B. DE C.V."),
    ("CIE", "CORPORACION INTERAMERICANA DE ENTRETENIMIENTO, S.A.B. DE C.V."),
    ("CMOCTEZ", "CORPORACION MOCTEZUMA, S.A.B. DE C.V."),
    ("CMR", "CMR, S.A.B. DE C.V."),
    ("COLLADO", "G COLLADO, S.A.B. DE C.V."),
    ("CONVER", "CONVERTIDORA INDUSTRIAL, S.A.B. DE C.V."),
    ("CREAL", "CREDITO REAL, S.A.B. DE C.V., SOFOM, E.N.R."),
    ("CTALPEK", "CONTROLADORA ALPEK, S.A.B. DE C.V."),
    ("CTAXTEL", "CONTROLADORA AXTEL, S.A.B. DE C.V."),
    ("CUERVO", "BECLE, S.A.B. DE C.V."),
    ("CULTIBA", "ORGANIZACIÓN CULTIBA, S.A.B. DE CV"),
    ("CYDSASA", "CYDSA, S.A.B. DE C.V."),
    ("DIABLOS", "DIABLOS ROJOS DEL MEXICO, S.A.P.I.B. DE C.V."),
    ("DINE", "DINE, S.A.B. DE C.V."),
    ("EDOARDO", "EDOARDOS MARTIN, S.A.B. DE C.V."),
    ("ELEKTRA", "GRUPO ELEKTRA, S.A.B. DE C.V."),
    ("FEMSA", "FOMENTO ECONÓMICO MEXICANO, S.A.B. DE C.V."),
    ("FINAMEX", "CASA DE BOLSA FINAMEX, S.A.B. DE C.V."),
    ("FINDEP", "FINANCIERA INDEPENDENCIA, S.A.B. DE C.V. SOFOM, E.N.R."),
    ("FRAGUA", "CORPORATIVO FRAGUA, S.A.B. DE C.V."),
    ("FRES", "FRESNILLO PLC"),
    ("GAP", "GRUPO AEROPORTUARIO DEL PACIFICO, S.A.B. DE C.V."),
    ("GAV", "ACOSTA VERDE, S.A.B. DE C.V."),
    ("GBM", "CORPORATIVO GBM, S.A.B. DE C. V."),
    ("GCARSO", "GRUPO CARSO, S.A.B. DE C.V."),
    ("GCC", "GCC, S.A.B. DE C.V."),
    ("GENTERA", "GENTERA, S.A.B. DE C.V."),
    ("GFAMSA", "GRUPO FAMSA, S.A.B. DE C.V."),
    ("GFINBUR", "GRUPO FINANCIERO INBURSA, S.A.B. DE C.V."),
    ("GFMULTI", "GRUPO FINANCIERO MULTIVA S.A.B. DE C.V."),
    ("GFNORTE", "GRUPO FINANCIERO BANORTE, S.A.B DE C.V."),
    ("GICSA", "GRUPO GICSA, S.A.B. DE C.V."),
    ("GIGANTE", "GRUPO GIGANTE, S.A.B. DE C.V."),
    ("GISSA", "GRUPO INDUSTRIAL SALTILLO, S.A.B. DE C.V."),
    ("GMD", "GRUPO MEXICANO DE DESARROLLO, S.A.B."),
    ("GMEXICO", "GRUPO MEXICO, S.A.B. DE C.V."),
    ("GMXT", "GMÉXICO TRANSPORTES, S.A.B. DE C.V."),
    ("GNP", "GRUPO NACIONAL PROVINCIAL, S.A.B."),
    ("GOMO", "GRUPO COMERCIAL GOMO, S.A. DE C.V."),
    ("GPH", "GRUPO PALACIO DE HIERRO, S.A.B. DE C.V."),
    ("GPROFUT", "GRUPO PROFUTURO, S.A.B. DE C.V."),
    ("GRUMA", "GRUMA, S.A.B. DE C.V."),
    ("HCITY", "PROMOTORA DE HOTELES NORTE 19, S.A.B. DE C.V."),
    ("HERDEZ", "GRUPO HERDEZ, S.A.B. DE C.V."),
    ("HIMEXSA", "HIMEXSA, S.A.B. DE C.V."),
    ("HOMEX", "DESARROLLADORA HOMEX, S.A.B. DE C.V."),
    ("HOTEL", "GRUPO HOTELERO SANTA FE, S.A.B. DE C.V."),
    ("IASASA", "INDUSTRIA AUTOMOTRIZ, S.A. DE C.V."),
    ("ICH", "INDUSTRIAS CH, S.A.B. DE C.V."),
    ("IDEAL", "IMPULSORA DEL DESARROLLO Y EL EMPLEO EN AMERICA LATINA, S.A.B. DE C.V."),
    ("INVEX", "INVEX CONTROLADORA, S.A.B. DE C.V."),
    ("KIMBER", "KIMBERLY - CLARK DE MEXICO S.A.B. DE C.V."),
    ("KOF", "COCA-COLA FEMSA, S.A.B. DE C.V."),
    ("KUO", "KUO, S.A.B. DE C.V."),
    ("LAB", "GENOMMA LAB INTERNACIONAL, S.A.B. DE C.V."),
    ("LACOMER", "LA COMER S.A.B. DE C.V."),
    ("LAMOSA", "GRUPO LAMOSA, S.A.B. DE C.V."),
    ("LASEG", "LA LATINOAMERICANA SEGUROS, S.A."),
    ("LASITE", "SITIOS LATINOAMÉRICA, S.A.B. DE C.V."),
    ("LIVEPOL", "EL PUERTO DE LIVERPOOL, S.A.B. DE C.V."),
    ("MEDICA", "MEDICA SUR, S.A.B. DE C.V."),
    ("MEGA", "MEGACABLE HOLDINGS, S.A.B. DE C.V."),
    ("MFRISCO", "MINERA FRISCO, S.A.B. DE C.V."),
    ("MINSA", "GRUPO MINSA, S.A.B. DE C.V."),
    ("NEMAK", "NEMAK, S.A.B. DE C.V."),
    ("NUTRISA", "GRUPO NUTRISA, S.A.B. DE C.V."),
    ("OMA", "GRUPO AEROPORTUARIO DEL CENTRO NORTE, S.A.B. DE C.V."),
    ("ORBIA", "ORBIA ADVANCE CORPORATION, S.A.B. DE C.V."),
    ("PASA", "PROMOTORA AMBIENTAL, S.A.B. DE C.V."),
    ("PE&OLES", "INDUSTRIAS PEÑOLES, S. A.B. DE C. V."),
    ("PINFRA", "PROMOTORA Y OPERADORA DE INFRAESTRUCTURA, S.A.B. DE C.V."),
    ("PLANI", "PLANIGRUPO LATAM, S.A.B. DE C.V."),
    ("POCHTEC", "GRUPO POCHTECA, S.A.B. DE C.V."),
    ("POSADAS", "GRUPO POSADAS, S.A.B. DE C.V."),
    ("PROCORP", "PROCORP, S.A.B. DE C.V."),
    ("PV", "PEÑA VERDE S.A.B."),
    ("Q", "QUÁLITAS CONTROLADORA, S.A.B. DE C.V."),
    ("QBINDUS", "Q.B. INDUSTRIAS, S.A. DE C.V."),
    ("QUMMA", "GRUPO QUMMA, S.A. DE C.V."),
    ("R", "REGIONAL, S.A.B. DE C.V."),
    ("RCENTRO", "GRUPO RADIO CENTRO, S.A.B. DE C.V."),
    ("RLH", "RLH PROPERTIES, S.A.B. DE C.V."),
    ("SARE", "SARE HOLDING, S.A.B. DE C.V."),
    ("SAVIA", "SAVIA, S.A. DE C.V."),
    ("SIMEC", "GRUPO SIMEC, S.A.B. DE C.V."),
    ("SITES1", "OPERADORA DE SITES MEXICANOS, S.A.B. DE C.V."),
    ("SORIANA", "ORGANIZACION SORIANA, S.A.B. DE C.V."),
    ("SPORT", "GRUPO SPORTS WORLD, S.A.B. DE C.V."),
    ("TEAK", "PROTEAK UNO, S.A.B. DE C.V."),
    ("TEKCHEM", "TEKCHEM, S.A.B. DE C.V."),
    ("TLEVISA", "GRUPO TELEVISA, S.A.B."),
    ("TMM", "GRUPO TMM, S.A."),
    ("TRAXION", "GRUPO TRAXIÓN S.A.B DE C.V."),
    ("TS", "TENARIS S.A."),
    ("UNIFIN", "UNIFIN FINANCIERA, S.A.B. DE C.V."),
    ("VALUEGF", "VALUE GRUPO FINANCIERO, S.A.B. DE C.V."),
    ("VASCONI", "GRUPO VASCONIA S.A.B."),
    ("VESTA", "CORPORACIÓN INMOBILIARIA VESTA, S.A.B. DE C.V."),
    ("VINTE", "VINTE VIVIENDAS INTEGRALES, S.A.B. DE C.V."),
    ("VISTA", "VISTA ENERGY, S.A.B. DE C.V."),
    ("VITRO", "VITRO, S.A.B. DE C.V."),
    ("VOLAR", "CONTROLADORA VUELA COMPAÑÍA DE AVIACIÓN, S.A.B. DE C.V."),
    ("WALMEX", "WAL - MART DE MEXICO, S.A.B. DE C.V."),
]

# sufijos comunes para acciones y fibras
variants = ["", "A", "B", "CPO", "O", "L", "N", "11", "12", "13", "14", "15", "16", "17"]

results = []

for clave, razon in tqdm(emisoras, total=len(emisoras), desc="Tickers"):
    found = []
    for v in variants:
        candidate = f"{clave}{v}.MX"
        try:
            t = yf.Ticker(candidate)
            hist = t.history(period="1d")
            if not hist.empty:
                found.append(candidate)
        except Exception:
            continue
    results.append((clave, razon, ", ".join(found) if found else "❌"))

df = pd.DataFrame(results, columns=["CLAVE EMISORA", "RAZON SOCIAL", "TICKER YF"])
df.to_excel("emisoras_bmv_yahoo.xlsx", index=False)
print("Archivo generado: emisoras_bmv_yahoo.xlsx")